Comment
Signed-off-by: shepz <gveschambre@datawire.io>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -10,212 +10,212 @@ on:
     types: [ labeled ]
 
 jobs:
-  check-commit:
-    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'release')))
-    runs-on: ubuntu-latest
-    outputs:
-      is_prepare_release: ${{ steps.check.outputs.is_prepare_release }}
-      telepresence_version: ${{ steps.check.outputs.telepresence_version }}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Check commit
-        id: check
-        uses: ./.github/actions/release/check-commit
-
-  prepare-release:
-    if: needs.check-commit.outputs.is_prepare_release == 1
-    runs-on: ubuntu-latest
-    needs: check-commit
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.GH_AUTO_RELEASE_TOKEN }}
-          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
-
-      - uses: actions/setup-go@v3
-        with:
-          go-version: '~1.21.0'
-
-      - name: Get release type
-        id: get_release_type
-        shell: bash
-        run: |
-          echo "is_ga=false" >> $GITHUB_ENV
-          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
-          echo "is_ga=true" >> $GITHUB_ENV
-          fi
-      - name: Prepare release
-        id: prepare
-        uses: ./.github/actions/release/prepare
-        with:
-          gh_auto_release_token: ${{ secrets.GH_AUTO_RELEASE_TOKEN }}
-          gh_auto_release_email: ${{ secrets.GH_AUTO_RELEASE_EMAIL }}
-          gh_auto_release_user: ${{ secrets.GH_AUTO_RELEASE_USER }}
-          is_ga: ${{ env.is_ga }}
-          telepresence_version: ${{ needs.check-commit.outputs.telepresence_version }}
-
-  itests_build_image:
-    if: needs.check-commit.outputs.is_prepare_release == 0
-    needs:
-      - check-commit
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-go@v3
-        with:
-          go-version: '~1.21.0'
-      - name: Build dev image
-        run: |
-          make save-tel2-image
-      - name: Upload image
-        uses: actions/upload-artifact@v3
-        with:
-          name: image
-          path: build-output/tel2-image.tar
-  itests_run:
-    strategy:
-      fail-fast: false
-      matrix:
-        runners:
-          - ubuntu-latest
-          - macos-latest
-          - windows-2019
-        #          - macOS-arm64
-        clusters:
-          - distribution: Kubeception
-            version: "1.26"
-    runs-on: ${{ matrix.runners }}
-    needs: itests_build_image
-    steps:
-      - uses: actions/checkout@v3
-  #      - uses: ./.github/actions/install-dependencies
-  #        name: install dependencies
-  #      - uses: actions/download-artifact@v3
-  #        with:
-  #          name: image
-  #      - run: make build
-  #      - uses: ./.github/actions/prepare-cluster
-  #        with:
-  #          kubeception-token: ${{ secrets.DEV_TELEPRESENCE_KUBECEPTION_TOKEN }}
-  #          kubeceptionProfile: small
-  #          gke-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
-  #          tel-image: tel2-image.tar
-  #          cluster-distribution: ${{ matrix.clusters.distribution }}
-  #          cluster-version: ${{ matrix.clusters.version }}
-  #        id: kluster
-  #      - uses: ./.github/actions/integration-tests
-  #        with:
-  #          kubeconfig: "${{ steps.kluster.outputs.kubeconfig }}"
-  #      - uses: ./.github/actions/upload-logs
-  #        env:
-  #          LOG_SUFFIX: "-${{ runner.os }}-${{ matrix.clusters.distribution }}-${{ matrix.clusters.version }}"
-  #        if: always()
-
-
-  build-release:
-    needs:
-      - check-commit
-      - itests_run
-    strategy:
-      fail-fast: false
-      matrix:
-        runners:
-          - ubuntu-latest
-#          - ubuntu-arm64
-          - macos-latest
-#          - macOS-arm64
-          - windows-2019
-    runs-on: ${{ matrix.runners }}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - uses: ./.github/actions/install-dependencies
-        name: install dependencies
-      - name: set version
-        shell: bash
-        run: echo "TELEPRESENCE_VERSION=${{ needs.check-commit.outputs.telepresence_version }}" >> $GITHUB_ENV
-      - name: generate binaries
-        run: make release-binary
-      - name: Upload binaries
-        uses: actions/upload-artifact@v3
-        with:
-          name: binaries
-          path: build-output/release
-          retention-days: 1
-#      - if: runner.os == 'Linux' && runner.arch == 'X64'
-#        name: Upload Docker image
+#  check-commit:
+#    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'release')))
+#    runs-on: ubuntu-latest
+#    outputs:
+#      is_prepare_release: ${{ steps.check.outputs.is_prepare_release }}
+#      telepresence_version: ${{ steps.check.outputs.telepresence_version }}
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          fetch-depth: 0
+#      - name: Check commit
+#        id: check
+#        uses: ./.github/actions/release/check-commit
+#
+#  prepare-release:
+#    if: needs.check-commit.outputs.is_prepare_release == 1
+#    runs-on: ubuntu-latest
+#    needs: check-commit
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          token: ${{ secrets.GH_AUTO_RELEASE_TOKEN }}
+#          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
+#
+#      - uses: actions/setup-go@v3
+#        with:
+#          go-version: '~1.21.0'
+#
+#      - name: Get release type
+#        id: get_release_type
+#        shell: bash
 #        run: |
-#          docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}"
-#          make push-tel2-image
-
-  release:
-    runs-on: ubuntu-latest
-    needs:
-      - build-release
-      - check-commit
-    env:
-      TELEPRESENCE_VERSION: ${{ needs.check-commit.outputs.telepresence_version }}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - uses: actions/setup-go@v3
-        with:
-          go-version: '~1.21.0'
-      - name: Create tag
-        id: create_tag
-        run: |
-          git config --global user.email "${{ secrets.GH_AUTO_RELEASE_EMAIL }}"
-          git config --global user.name "${{ secrets.GH_AUTO_RELEASE_USER }}"
-          git tag --annotate --message='${{ env.TELEPRESENCE_VERSION }}' ${{ env.TELEPRESENCE_VERSION }}
-          git tag --annotate --message='${{ env.TELEPRESENCE_VERSION }}' rpc/${{ env.TELEPRESENCE_VERSION }}
-          git push origin {,rpc/}${{ env.TELEPRESENCE_VERSION }}
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-      - name: Determine if version is RC or GA
-        id: semver_check
-        run: |
-          if [[ "${{ env.TELEPRESENCE_VERSION }}" =~ ^v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+$ ]]; then
-          echo "MAKE_LATEST=false" >> $GITHUB_ENV
-          echo "PRERELEASE=true" >> $GITHUB_ENV
-          else
-          echo "MAKE_LATEST=true" >> $GITHUB_ENV
-          echo "PRERELEASE=false" >> $GITHUB_ENV
-          fi
-      - name: Create release
-        uses: ncipollo/release-action@v1
-        with:
-          artifacts: "binaries/*"
-          token: ${{ secrets.GITHUB_TOKEN }}
-          prerelease: ${{ env.PRERELEASE }}
-          makeLatest: ${{ env.MAKE_LATEST }}
-          tag: ${{ env.TELEPRESENCE_VERSION }}
-          body: |
-            ## Official Release Artifacts
-            ### Linux
-               - 📦 [telepresence-linux-amd64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-linux-amd64)
-               - 📦 [telepresence-linux-arm64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-linux-arm64)
-            ### OSX Darwin
-               - 📦 [telepresence-darwin-amd64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-darwin-amd64)
-               - 📦 [telepresence-darwin-arm64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-darwin-arm64)
-            ### Windows
-               - 📦 [telepresence-windows-amd64.zip](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-windows-amd64.zip)
-
-            For more builds across platforms and architectures, see the `Assets` section below.
-            And for more information, visit our [installation docs](https://www.telepresence.io/docs/latest/quick-start/).
-
-            ![Assets](https://static.scarf.sh/a.png?x-pxid=d842651a-2e4d-465a-98e1-4808722c01ab)
+#          echo "is_ga=false" >> $GITHUB_ENV
+#          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+#          echo "is_ga=true" >> $GITHUB_ENV
+#          fi
+#      - name: Prepare release
+#        id: prepare
+#        uses: ./.github/actions/release/prepare
+#        with:
+#          gh_auto_release_token: ${{ secrets.GH_AUTO_RELEASE_TOKEN }}
+#          gh_auto_release_email: ${{ secrets.GH_AUTO_RELEASE_EMAIL }}
+#          gh_auto_release_user: ${{ secrets.GH_AUTO_RELEASE_USER }}
+#          is_ga: ${{ env.is_ga }}
+#          telepresence_version: ${{ needs.check-commit.outputs.telepresence_version }}
+#
+#  itests_build_image:
+#    if: needs.check-commit.outputs.is_prepare_release == 0
+#    needs:
+#      - check-commit
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - uses: actions/setup-go@v3
+#        with:
+#          go-version: '~1.21.0'
+#      - name: Build dev image
+#        run: |
+#          make save-tel2-image
+#      - name: Upload image
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: image
+#          path: build-output/tel2-image.tar
+#  itests_run:
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        runners:
+#          - ubuntu-latest
+#          - macos-latest
+#          - windows-2019
+#        #          - macOS-arm64
+#        clusters:
+#          - distribution: Kubeception
+#            version: "1.26"
+#    runs-on: ${{ matrix.runners }}
+#    needs: itests_build_image
+#    steps:
+#      - uses: actions/checkout@v3
+#  #      - uses: ./.github/actions/install-dependencies
+#  #        name: install dependencies
+#  #      - uses: actions/download-artifact@v3
+#  #        with:
+#  #          name: image
+#  #      - run: make build
+#  #      - uses: ./.github/actions/prepare-cluster
+#  #        with:
+#  #          kubeception-token: ${{ secrets.DEV_TELEPRESENCE_KUBECEPTION_TOKEN }}
+#  #          kubeceptionProfile: small
+#  #          gke-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
+#  #          tel-image: tel2-image.tar
+#  #          cluster-distribution: ${{ matrix.clusters.distribution }}
+#  #          cluster-version: ${{ matrix.clusters.version }}
+#  #        id: kluster
+#  #      - uses: ./.github/actions/integration-tests
+#  #        with:
+#  #          kubeconfig: "${{ steps.kluster.outputs.kubeconfig }}"
+#  #      - uses: ./.github/actions/upload-logs
+#  #        env:
+#  #          LOG_SUFFIX: "-${{ runner.os }}-${{ matrix.clusters.distribution }}-${{ matrix.clusters.version }}"
+#  #        if: always()
+#
+#
+#  build-release:
+#    needs:
+#      - check-commit
+#      - itests_run
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        runners:
+#          - ubuntu-latest
+##          - ubuntu-arm64
+#          - macos-latest
+##          - macOS-arm64
+#          - windows-2019
+#    runs-on: ${{ matrix.runners }}
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          fetch-depth: 0
+#      - uses: ./.github/actions/install-dependencies
+#        name: install dependencies
+#      - name: set version
+#        shell: bash
+#        run: echo "TELEPRESENCE_VERSION=${{ needs.check-commit.outputs.telepresence_version }}" >> $GITHUB_ENV
+#      - name: generate binaries
+#        run: make release-binary
+#      - name: Upload binaries
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: binaries
+#          path: build-output/release
+#          retention-days: 1
+##      - if: runner.os == 'Linux' && runner.arch == 'X64'
+##        name: Upload Docker image
+##        run: |
+##          docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}"
+##          make push-tel2-image
+#
+#  release:
+#    runs-on: ubuntu-latest
+#    needs:
+#      - build-release
+#      - check-commit
+#    env:
+#      TELEPRESENCE_VERSION: ${{ needs.check-commit.outputs.telepresence_version }}
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          fetch-depth: 0
+#      - uses: actions/setup-go@v3
+#        with:
+#          go-version: '~1.21.0'
+#      - name: Create tag
+#        id: create_tag
+#        run: |
+#          git config --global user.email "${{ secrets.GH_AUTO_RELEASE_EMAIL }}"
+#          git config --global user.name "${{ secrets.GH_AUTO_RELEASE_USER }}"
+#          git tag --annotate --message='${{ env.TELEPRESENCE_VERSION }}' ${{ env.TELEPRESENCE_VERSION }}
+#          git tag --annotate --message='${{ env.TELEPRESENCE_VERSION }}' rpc/${{ env.TELEPRESENCE_VERSION }}
+#          git push origin {,rpc/}${{ env.TELEPRESENCE_VERSION }}
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#      - name: Determine if version is RC or GA
+#        id: semver_check
+#        run: |
+#          if [[ "${{ env.TELEPRESENCE_VERSION }}" =~ ^v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+$ ]]; then
+#          echo "MAKE_LATEST=false" >> $GITHUB_ENV
+#          echo "PRERELEASE=true" >> $GITHUB_ENV
+#          else
+#          echo "MAKE_LATEST=true" >> $GITHUB_ENV
+#          echo "PRERELEASE=false" >> $GITHUB_ENV
+#          fi
+#      - name: Create release
+#        uses: ncipollo/release-action@v1
+#        with:
+#          artifacts: "binaries/*"
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          prerelease: ${{ env.PRERELEASE }}
+#          makeLatest: ${{ env.MAKE_LATEST }}
+#          tag: ${{ env.TELEPRESENCE_VERSION }}
+#          body: |
+#            ## Official Release Artifacts
+#            ### Linux
+#               - 📦 [telepresence-linux-amd64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-linux-amd64)
+#               - 📦 [telepresence-linux-arm64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-linux-arm64)
+#            ### OSX Darwin
+#               - 📦 [telepresence-darwin-amd64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-darwin-amd64)
+#               - 📦 [telepresence-darwin-arm64](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-darwin-arm64)
+#            ### Windows
+#               - 📦 [telepresence-windows-amd64.zip](https://app.getambassador.io/download/tel2oss/releases/download/${{ github.ref_name }}/telepresence-windows-amd64.zip)
+#
+#            For more builds across platforms and architectures, see the `Assets` section below.
+#            And for more information, visit our [installation docs](https://www.telepresence.io/docs/latest/quick-start/).
+#
+#            ![Assets](https://static.scarf.sh/a.png?x-pxid=d842651a-2e4d-465a-98e1-4808722c01ab)
 
   trigger-releases:
     runs-on: ubuntu-latest
-    needs:
-      - release
-      - check-commit
+#    needs:
+#      - release
+#      - check-commit
     env:
-      TELEPRESENCE_VERSION: ${{ needs.check-commit.outputs.telepresence_version }}
+      TELEPRESENCE_VERSION: "v2.20.0-rc.2"
     strategy:
       fail-fast: false
       matrix:
